services:
  db:
    image: postgis/postgis:15-3.3-alpine
    container_name: uav_db
    environment:
      - POSTGRES_USER=uav_user
      - POSTGRES_PASSWORD=strong_password
      - POSTGRES_DB=uav_analytics
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U uav_user -d uav_analytics"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: uav_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app # Для live-reload кода при разработке
    environment:
      - POSTGRES_USER=uav_user
      - POSTGRES_PASSWORD=strong_password
      - POSTGRES_DB=uav_analytics
      - DB_HOST=db # Указываем, что БД находится в сервисе 'db'
    depends_on:
      db:
        condition: service_healthy # Ждем, пока БД будет готова принимать подключения

  frontend:
    build: ./frontend
    container_name: uav_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_API_URL=http://localhost:8000
      - REACT_APP_ENV=development
      - REACT_APP_ENABLE_DEBUG=true
    depends_on:
      - backend

volumes:
  postgres_data: